### ISSUE TITLE
translate() uses incorrect codons for DNA to protein conversion

### ISSUE THREAD

**Issue by poppn** [BioGenies/tidysq#95]
The codon table used by translate() has 4 codons swapped, where the wrong amino acid is called (specifically TTN codons).

```{r}

test_tib <- tibble(codons = c("TTA", "TTC", "TTG", "TTT"),
                   correct_aa = c("L", "F", "L", "F")) %>%
  mutate(tidysq_codons = sq(codons),
         tidysq_aa = translate(tidysq_codons))

test_tib

A tibble: 4 × 4
  codons correct_aa tidysq_codons tidysq_aa
  <chr>  <chr>      <dna_bsc>     <ami_bsc>
1 TTA    L          TTA <3>       F <1>    
2 TTC    F          TTC <3>       L <1>    
3 TTG    L          TTG <3>       F <1>    
4 TTT    F          TTT <3>       L <1>    

```

**Comment by ErdaradunGaztea** [comment]
Yup, turns out I switched two codons while hardcoding the values. Dominik fixed it and it shouldn't break anymore, now that all codons are covered by tests instead of just a few selected ones. However, we won't be submitting this to CRAN yet, so the fix is currently* available on devel branch; you can install it with:

```r
devtools::install_github("BioGenies/tidysq@devel")
```

*) once pull request #96 is checked and merged, that is
